In [1]:
import pandas as pd
import numpy as np
import sqlalchemy as sal

In [44]:
df = pd.read_csv("netflix_titles.csv")

In [57]:
engine = sal.create_engine("mssql+pyodbc://@LAPTOP-DLBO22F9\\SQLEXPRESS/Netflix_Content_Analytics" "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes" "&TrustServerCertificate=yes")
conn=engine.connect()

C:\Users\sasri\AppData\Local\Temp\ipykernel_1488\1346782021.py:3: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  conn=engine.connect()

In [58]:
from sqlalchemy.types import NVARCHAR

# Load the data into sql server
df.to_sql('netflix_raw', con=conn, index=False, if_exists='replace', dtype={'title': NVARCHAR()})
conn.close()

In [9]:
# df.shape or
len(df)

8807

In [14]:
df[df.show_id == 's5023']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5022,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...

In [34]:
# Find the max length of the string for each column

#max(df.show_id.str.len())
#max(df.type.str.len())
#max(df.title.str.len())
#max(df.director.str.len())
#max(df.country.str.len())
#max(df.date_added.str.len())
#####max(df.cast.dropna().str.len())
#max(df.rating.str.len())
#max(df.duration.str.len())
#max(df.listed_in.str.len())
max(df.description.str.len())

248

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [61]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64